"""empty message

Revision ID: 2df67323fe49
Revises: 
Create Date: 2018-04-17 14:12:38.736417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df67323fe49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_history')
    op.drop_column('games', 'guesses_str')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('guesses_str', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('search_history',
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('movie_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['movie_title'], ['movies.title'], name='search_history_movie_title_fkey'),
    sa.ForeignKeyConstraint(['username'], ['users.username'], name='search_history_username_fkey')
    )
    # ### end Alembic commands ###
