"""empty message

Revision ID: 4259901c85b5
Revises: 2df67323fe49
Create Date: 2018-04-17 14:13:58.039931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4259901c85b5'
down_revision = '2df67323fe49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_history',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('movie_title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['movie_title'], ['movies.title'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_history')
    # ### end Alembic commands ###
